source 'https://rubygems.org'

gem 'rake'
gem 'ib'
# Add your dependencies here:
Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Media Info'
  app.frameworks += ['AssetsLibrary', 'MobileCoreServices']
end